### ISSUE TITLE
Implement PDF text extraction

### ISSUE THREAD

**Issue by ErykDarnowski** [ErykDarnowski/ts-test-extractor#1]
## TODO

- [x] Add `venv` instructions to `README.md`
- [x] Implement (for all files at once)
- [x] Fix issue with Polish diacritic characters

## Resources

- <https://www.geeksforgeeks.org/extract-text-from-pdf-file-using-python/>
- <https://stackoverflow.com/questions/70848337/how-to-read-multiple-pdf-from-a-folder-one-by-one>
