### ISSUE TITLE
Implement output

### ISSUE THREAD

**Issue by ErykDarnowski** [ErykDarnowski/ts-test-extractor#3]
## TODO

- [x] Add check for misaligned values (based on lengths)
- [x] Add formatting fixes
  - Answers (A, B, C): `/\s(?=[A-Z]\.)/gm` (replace)
- [x] Implement writing to **JSON** file

## Resources

- <https://regex101.com/>
- <https://note.nkmk.me/en/python-split-rsplit-splitlines-re/#split-a-string-by-regex-resplit>
